---
# Tells flux to configure itself with the stuff in this repo
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/johnjaredprater/infrastructure
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: web-server
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/johnjaredprater/web_server
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gym-track-core
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/johnjaredprater/gym_track_core
---
# Tells flux which repo & file to monitor & apply changes to the Kubernetes cluster
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: web-server
  namespace: flux-system
spec:
  interval: 1m0s
  path: "./deploy/manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: web-server
  targetNamespace: default
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gym-track-core
  namespace: flux-system
spec:
  interval: 1m0s
  path: "./deploy/manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gym-track-core
  targetNamespace: default
